<?php

$labels = array(
	'name'                  => _x( 'Facilities', 'Post Type General Name', 'text_domain' ),
	'singular_name'         => _x( 'Facility', 'Post Type Singular Name', 'text_domain' ),
	'menu_name'             => __( 'Facilities', 'text_domain' ),
	'name_admin_bar'        => __( 'Facility', 'text_domain' ),
	'archives'              => __( 'Facility Archives', 'text_domain' ),
	'attributes'            => __( 'Facility Attributes', 'text_domain' ),
	'parent_item_colon'     => __( 'Parent Facility:', 'text_domain' ),
	'all_items'             => __( 'All Facilities', 'text_domain' ),
	'add_new_item'          => __( 'Add New Facility', 'text_domain' ),
	'add_new'               => __( 'Add New Facility', 'text_domain' ),
	'new_item'              => __( 'New Facility', 'text_domain' ),
	'edit_item'             => __( 'Edit Facility', 'text_domain' ),
	'update_item'           => __( 'Update Item', 'text_domain' ),
	'view_item'             => __( 'View Facility', 'text_domain' ),
	'view_items'            => __( 'View Facilities', 'text_domain' ),
	'search_items'          => __( 'Search Facility', 'text_domain' ),
	'not_found'             => __( 'Facility Not found', 'text_domain' ),
	'not_found_in_trash'    => __( 'Facility Not found in Trash', 'text_domain' ),
	'featured_image'        => __( 'Featured Image', 'text_domain' ),
	'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
	'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
	'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
	'insert_into_item'      => __( 'Insert into Facility', 'text_domain' ),
	'uploaded_to_this_item' => __( 'Uploaded to this v', 'text_domain' ),
	'items_list'            => __( 'Facilities list', 'text_domain' ),
	'items_list_navigation' => __( 'Facilities list navigation', 'text_domain' ),
	'filter_items_list'     => __( 'Filter Facilities list', 'text_domain' ),
);

$args = array(
	'label'                 => __( 'Facility', 'text_domain' ),
	'description'           => __( 'Future Foam Facilities', 'text_domain' ),
	'labels'                => $labels,
	'supports'              => array( 'title', 'custom-fields', 'page-attributes'  ),
	'hierarchical'          => false,
	'public'                => true,
	'show_ui'               => true,
	'show_in_menu'          => true,
	// 'menu_position'         => 5,
	'menu_icon'             => 'dashicons-building',
	'show_in_admin_bar'     => true,
	'show_in_nav_menus'     => true,
	'can_export'            => true,
	'has_archive'           => true,
	'exclude_from_search'   => true,
	'publicly_queryable'    => true,
	'capability_type'       => 'page',
	'show_in_rest'          => false,
);

register_post_type( 'Facility', $args );